### ISSUE TITLE
How to send text message with attachments ?

### ISSUE THREAD

**Issue by hitamu** [mdibaiee/slackbot-api#2]
I'm looking for a guide how to send message with attachments.
Currently, document doesn't have any example about it.
Thanks

**Comment by hitamu** [comment]
After a while looking in the [source code](https://github.com/mdibaiee/slackbot-api/blob/master/src/bot.js#L560), I found out that option `websocket` must be false to using `chat.postMessage` method.

And it's worked.
```
    const attachments = new bot.Attachments();
    attachments.good('You look good!');
    const options = {
        websocket: false,
        attachments: attachments
    }
    bot.sendMessage(MY_CHANNEL, "Hello", options);
```
But for more convenient, please mention a few word in this document page [Attachments](https://mdibaiee.gitbooks.io/slackbot-api/content/Documentation/attachments.html)

**Comment by mdibaiee** [comment]
@hitamu glad you found out your answer, sure I will add it to the documentation! :+1:
